---
- name: APT Update & Upgrade
  hosts: all
  become: yes  # Ejecutar con privilegios de superusuario

  tasks:
    - name: APT Update
      apt:
        update_cache: yes

    - name: APT upgrade
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Restart check
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      reboot:
      when: reboot_required.stat.exists
